# Generated by Django 3.2.9 on 2022-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneno', models.IntegerField(default=0)),
                ('post', models.CharField(max_length=100)),
                ('startyear', models.DateField(default=0)),
                ('passyear', models.DateField(default=0)),
                ('linkedin', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneno', models.IntegerField(default=0)),
                ('post', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('linkedin', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
            ],
        ),
    ]
