# Generated by Django 3.2.9 on 2022-05-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('phoneNo', models.IntegerField()),
                ('post', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('linkedin', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
            ],
        ),
    ]
