# Generated by Django 3.2.9 on 2022-10-26 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 23, 22, 10, 580981)),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 23, 22, 10, 580950)),
        ),
    ]
