# Generated by Django 3.2.9 on 2022-05-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='StudentName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Year',
            new_name='year',
        ),
    ]
