# Generated by Django 3.2.9 on 2022-06-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
