# Generated by Django 3.2.9 on 2022-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='images/Events')),
                ('StartDate', models.DateField(default=0)),
                ('EndDate', models.DateField(default=0)),
                ('Location', models.CharField(blank=True, max_length=500)),
                ('Link', models.CharField(blank=True, max_length=5000)),
                ('Description', models.CharField(blank=True, max_length=5000)),
                ('EventTense', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='post',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='startyear',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='image',
            field=models.ImageField(upload_to='images/Alumni'),
        ),
    ]
