# Generated by Django 3.2.9 on 2022-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220511_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phoneNo',
        ),
        migrations.AddField(
            model_name='student',
            name='phoneno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
