# Generated by Django 3.2.9 on 2022-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220605_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='facebook',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='instagram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='linkedin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='facebook',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='instagram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.CharField(max_length=200),
        ),
    ]
