# Generated by Django 3.2.9 on 2022-07-18 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(13, 13, 25, 600909)),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='Link',
            field=models.CharField(blank=True, default='no link', max_length=5000),
        ),
    ]
