# Generated by Django 3.2.9 on 2022-07-18 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220718_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(13, 13, 45, 621724)),
        ),
    ]
