# Generated by Django 3.2.9 on 2022-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gallery_sponsers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
