# Generated by Django 3.2.9 on 2022-08-15 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EndDate',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartDate',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(21, 3, 25, 291212)),
        ),
    ]
