# Generated by Django 3.2.9 on 2022-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220815_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='EndDate',
            field=models.DateTimeField(default='15-Aug-22'),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartDate',
            field=models.DateTimeField(default='15-Aug-22'),
        ),
    ]
