# Generated by Django 3.2.9 on 2022-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220815_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EndDate',
            field=models.DateTimeField(default='Mon-Aug-22'),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartDate',
            field=models.DateTimeField(default='Mon-Aug-22'),
        ),
    ]
