# Generated by Django 3.2.9 on 2022-08-15 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220815_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EndDate',
            field=models.DateTimeField(default=datetime.date(2022, 8, 15)),
        ),
        migrations.AlterField(
            model_name='event',
            name='StartDate',
            field=models.DateTimeField(default=datetime.date(2022, 8, 15)),
        ),
    ]
