# Generated by Django 3.2.9 on 2022-08-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220815_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
